# docker-compose configuration file for running a Django container
# that uses Redis as main cache database and Postgres as the relational one.
version: "3.9"
   
services:

  cache:
    image: redis
    hostname: cache
    restart: unless-stopped
    ports:
      - "6379:6379"

  db:
    image: postgres
    hostname: db
    volumes:
      # local db folder has to exist !
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_DB=openapi
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"

  openapi_backend:
    build: .
    hostname: backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=openapi
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    restart: always
    depends_on:
      - db
      - cache
      
