# Generated by Django 4.1 on 2022-09-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('fps', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Thumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True, max_length=256, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('embeded_url', models.URLField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail', models.URLField(blank=True, max_length=1024, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('quality', models.CharField(max_length=10)),
                ('fps', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True, max_length=256, null=True)),
                ('mime_type', models.CharField(max_length=20)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_max', models.URLField(blank=True, max_length=1024, null=True)),
                ('url', models.URLField(blank=True, max_length=256, null=True)),
                ('account_type', models.CharField(choices=[('basic', 'Basic'), ('business', 'Business'), ('live business', 'Live business'), ('live premium', 'Live premium'), ('live pro', 'Live pro'), ('plus', 'Plus'), ('pro', 'Pro'), ('pro unlimited', 'Pro unlimited'), ('producer', 'Producer')], default='basic', max_length=100)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
    ]
