# Generated by Django 4.1 on 2022-09-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_thumb_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
